services:
  mysql:
    image: mysql:8.2
    container_name: c15-41-t-java-react_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    networks:
      - localnet

  pma:
    depends_on:
      - mysql
    image: phpmyadmin
    container_name: c15-41-t-java-react_pma
    restart: always
    ports:
      - 81:80
    environment:
      - PMA_HOST=mysql
    networks:
      - localnet

  backend:
    depends_on:
      - mysql
    container_name: c15-41-t-java-react_backend
    restart: always
    build:
      context: ./LibraryBackEnd
      dockerfile: Dockerfile
    environment:
      - DB_HOSTNAME=mysql:3306
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
      - API_SECURITY_SECRET
      - EMAIL_USERNAME
      - EMAIL_PASSWORD
      - API_SECRET_CLOUDINARY
    ports:
      - "8080:8080"
    networks:
      - localnet

  frontend:
    depends_on:
      - backend
    container_name: c15-41-t-java-react_frontend
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_HOST
    restart: always
    ports:
      - "80:80"
    networks:
      - localnet

volumes:
  mysql-data:


networks:
  localnet:
    driver: bridge
