services:
  mysql:
    image: mysql:8.2
    container_name: c15-41-t-java-react_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - type: bind
        source: ./LibraryBackEnd/src/main/resources/scripts/ScritpSchemaBibliotech.sql
        target: /docker-entrypoint-initdb.d/ScritpSchemaBibliotech.sql
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    networks:
      - localnet

  pma:
    depends_on:
      - mysql
    image: phpmyadmin
    container_name: c15-41-t-java-react_pma
    restart: always
    ports:
      - 81:80
    environment:
      - PMA_HOST=mysql
    networks:
      - localnet

  backend:
    depends_on:
      - mysql
    container_name: c15-41-t-java-react_backend
    build:
      context: ./LibraryBackEnd
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - localnet

  frontend:
    depends_on:
      - backend
    container_name: c15-41-t-java-react_frontend
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    networks:
      - localnet

volumes:
  mysql-data:


networks:
  localnet:
    driver: bridge
